export const ARAB_COUNTRIES = [
  {
    code: "EG",
    name: "Egypt",
    nameAr: "مصر",
    currency: "EGP",
    currencySymbol: "ج.م",
    locale: "ar-EG",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    nameAr: "المملكة العربية السعودية",
    currency: "SAR",
    currencySymbol: "ر.س",
    locale: "ar-SA",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    nameAr: "الإمارات العربية المتحدة",
    currency: "AED",
    currencySymbol: "د.إ",
    locale: "ar-AE",
  },
  {
    code: "KW",
    name: "Kuwait",
    nameAr: "الكويت",
    currency: "KWD",
    currencySymbol: "د.ك",
    locale: "ar-KW",
  },
  {
    code: "QA",
    name: "Qatar",
    nameAr: "قطر",
    currency: "QAR",
    currencySymbol: "ر.ق",
    locale: "ar-QA",
  },
  {
    code: "BH",
    name: "Bahrain",
    nameAr: "البحرين",
    currency: "BHD",
    currencySymbol: "د.ب",
    locale: "ar-BH",
  },
  {
    code: "OM",
    name: "Oman",
    nameAr: "عمان",
    currency: "OMR",
    currencySymbol: "ر.ع",
    locale: "ar-OM",
  },
  {
    code: "JO",
    name: "Jordan",
    nameAr: "الأردن",
    currency: "JOD",
    currencySymbol: "د.أ",
    locale: "ar-JO",
  },
  {
    code: "LB",
    name: "Lebanon",
    nameAr: "لبنان",
    currency: "LBP",
    currencySymbol: "ل.ل",
    locale: "ar-LB",
  },
  {
    code: "SY",
    name: "Syria",
    nameAr: "سوريا",
    currency: "SYP",
    currencySymbol: "ل.س",
    locale: "ar-SY",
  },
  {
    code: "IQ",
    name: "Iraq",
    nameAr: "العراق",
    currency: "IQD",
    currencySymbol: "د.ع",
    locale: "ar-IQ",
  },
  {
    code: "YE",
    name: "Yemen",
    nameAr: "اليمن",
    currency: "YER",
    currencySymbol: "ر.ي",
    locale: "ar-YE",
  },
  {
    code: "LY",
    name: "Libya",
    nameAr: "ليبيا",
    currency: "LYD",
    currencySymbol: "د.ل",
    locale: "ar-LY",
  },
  {
    code: "TN",
    name: "Tunisia",
    nameAr: "تونس",
    currency: "TND",
    currencySymbol: "د.ت",
    locale: "ar-TN",
  },
  {
    code: "DZ",
    name: "Algeria",
    nameAr: "الجزائر",
    currency: "DZD",
    currencySymbol: "د.ج",
    locale: "ar-DZ",
  },
  {
    code: "MA",
    name: "Morocco",
    nameAr: "المغرب",
    currency: "MAD",
    currencySymbol: "د.م",
    locale: "ar-MA",
  },
  {
    code: "SD",
    name: "Sudan",
    nameAr: "السودان",
    currency: "SDG",
    currencySymbol: "ج.س",
    locale: "ar-SD",
  },
  {
    code: "PS",
    name: "Palestine",
    nameAr: "فلسطين",
    currency: "ILS",
    currencySymbol: "ش.ج",
    locale: "ar-PS",
  },
  {
    code: "SO",
    name: "Somalia",
    nameAr: "الصومال",
    currency: "SOS",
    currencySymbol: "ش.ص",
    locale: "ar-SO",
  },
  {
    code: "DJ",
    name: "Djibouti",
    nameAr: "جيبوتي",
    currency: "DJF",
    currencySymbol: "ف.ج",
    locale: "ar-DJ",
  },
  {
    code: "KM",
    name: "Comoros",
    nameAr: "جزر القمر",
    currency: "KMF",
    currencySymbol: "ف.ج.ق",
    locale: "ar-KM",
  },
  {
    code: "MR",
    name: "Mauritania",
    nameAr: "موريتانيا",
    currency: "MRU",
    currencySymbol: "أ.م",
    locale: "ar-MR",
  },
];
